eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7850/eureka/

server:
  port: 12853

spring:
  application:
    name: business

  zipkin:
    base-url: http://localhost:9411

feign:
  hystrix:
    enabled: true