eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7850/eureka/

server:
  port: 16523

spring:
  application:
    name: entrance-http

  zipkin:
    base-url: http://localhost:7851

feign:
  hystrix:
    enabled: true