eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7850/eureka/

server:
  port: 16523

spring:
  application:
    name: entrance-http

  zipkin:
    locator:
      discovery:
        enabled: true
    service:
      name: sleuth

feign:
  hystrix:
    enabled: true