eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7850/eureka/

server:
  port: 12463

spring:
  application:
    name: payapi

  zipkin:
    locator:
      discovery:
        enabled: true
    service:
      name: sleuth