server:
  port: 7850

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/